title: YamiGuard Wiki
remote_theme: just-the-docs/just-the-docs@v0.8.2
repository: cvtzv/yg.kdev.world
plugins:
  - jekyll-remote-theme
color_scheme: dark
footer_content: false
footer:
  content: false
  custom: true
sass:
  sass_dir: _sass
