title: YamiGuard Wiki
remote_theme: just-the-docs/just-the-docs@v0.8.2
repository: cvtzv/yg.kdev.world
plugins:
  - jekyll-remote-theme
color_scheme: dark
nav:
     - title: Главная
       url: /
     - title: Команды
       url: /commands.html
     - title: FAQ
       url: /faq.md
