title: YamiGuard Wiki
remote_theme: just-the-docs/just-the-docs@v0.8.2
repository: cvtzv/yg.kdev.world
plugins:
  - jekyll-remote-theme
color_scheme: dark

aux_links: {} 
nav_external_links: [] 

nav:
  - title: Главняа
    url: /
  - title: Команды
    url: /commands.md
  - title: FAQ
    url: /faq.md
